exports.seed = (knex, Promise) ->
  knex("chats_rooms_users").del()
  .then -> knex("chats_rooms").del()
  .then -> knex("chats_room_statuses").del()
  .then -> knex("chats_messages").del()
  .then -> knex("chats").del()
  .then -> knex("logs").del()
  .then -> knex("log_types").del()
  .then -> knex("sharing_items").del()
  .then -> knex("sharing_item_types").del()
  .then -> knex("sharing_item_statuses").del()
  .then -> knex("sharing_price_types").del()
  .then -> knex("sharing_categories").del()
  .then -> knex("users").del()
  .then -> knex("user_statuses").del()
  .then -> knex("user_roles").del()
  .then -> knex("languages").del()
  .then -> knex("locations").del()