exports.seed = (knex, Promise) ->
  _ins = (name="") ->
    values =
      slug: name.toLowerCase().replace(/&/g, "").replace /[,\s]+/g, "-"
      name: name
    (knex "locations").insert values

  Promise.join(
    # Deletes ALL existing entries
    knex("locations").del(),

    _ins("Abdullah Al-Salem"),
    _ins("Abraq Khaitan"),
    _ins("Abu Fteira"),
    _ins("Abu Halifa"),
    _ins("Adiliya"),
    _ins("Adan"),
    _ins("Ahmadi"),
    _ins("Al-Jabriya"),
    _ins("Al-Zour"),
    _ins("Andalus"),
    _ins("Ardiyah"),
    _ins("Bayan"),
    _ins("Bayan"),
    _ins("Bi-di"),
    _ins("Bnied Al-Gar"),
    _ins("Daiya"),
    _ins("Dasman"),
    _ins("Doha"),
    _ins("Fahaheel"),
    _ins("Faiha"),
    _ins("Fardaws"),
    _ins("Farwaniyah"),
    _ins("Fintas"),
    _ins("Funaitīs"),
    _ins("Ghirnata"),
    _ins("Hadiya"),
    _ins("Hawally"),
    _ins("Hittin"),
    _ins("Jabir al-Ahmad City"),
    _ins("Jabriya"),
    _ins("Jahra"),
    _ins("Jibla"),
    _ins("Jleeb Al-Shuyoukh"),
    _ins("Keifan"),
    _ins("Khaitan"),
    _ins("Khaldiya"),
    _ins("Kuwait City"),
    _ins("Mahboula"),
    _ins("Maidan Hawalli"),
    _ins("Mangaf"),
    _ins("Mansouriya"),
    _ins("Mirgab"),
    _ins("Mishref"),
    _ins("Misila"),
    _ins("Mubarak aj-Jabir suburb"),
    _ins("Mubarak al-Kabeer"),
    _ins("Nahdha"),
    _ins("Nigra"),
    _ins("Nuzha"),
    _ins("Omariya"),
    _ins("Qadsiya"),
    _ins("Qurain"),
    _ins("Qurtuba"),
    _ins("Qusur"),
    _ins("Rabiya"),
    _ins("Rai"),
    _ins("Rawdah"),
    _ins("Riqqah"),
    _ins("Rumaithiya"),
    _ins("Sabah Al-Nasser"),
    _ins("Sabah Al-Salem"),
    _ins("Sabahiyah"),
    _ins("Sabhan"),
    _ins("Salhiya"),
    _ins("Salmiya"),
    _ins("Salwa"),
    _ins("Sawabir"),
    _ins("Sha-ab"),
    _ins("Shammiya"),
    _ins("Sharq"),
    _ins("Shuwaikh"),
    _ins("Sulaibikhat"),
    _ins("Surra"),
    _ins("Udailiya"),
    _ins("Wafra"),
    _ins("Yarmuk")
  )