module.exports =
	'account-index':      require './account'
	'account-manage':     require './account/manage'
	'auth-forgot':        require './auth/login'
	'auth-login':         require './auth/login'
	'auth-logout':        require './auth/logout'
	'auth-reset':         require './auth/login'
	'auth-signup':        require './auth/signup'
	'classified-edit':    require './classified/edit'
	'classified-post':    require './classified/post'
	'classified-search':  require './classified/search'
	'classified-single':  require './classified/single'
	'guest-post':         require './classified/post'
	'guest-single':       require './classified/single'
	'landing':            require './landing'
	'privacy':            require './privacy'
	'terms':              require './terms'