###
**MainView**
------------

TODO: Rewrite this

This is the base view for all pages in the App. All pages must inherit
the properties in the view.

The different functions and properties defined
here get used by the ViewManager controller and enables the controller to
neatly cleanup and restart views.
###
module.exports =
  idAttribute: "_id"

  ###
  ## *initialize():*
  This function gets called by Backbone whenever we instantiate an Object from
  this view. Here we setup some common resources for all our child
  models to play with.
  ###
  initialize: (options={}) ->
    @resources = App.Resources
    @start()

  start: ->


  ###
  ## *name:*
  Here goes the name of the view. This is used in console statements
  to help debug the app. So in your view you would use something like

      console.log @name, "Message"

  and this makes it easy to filter out console messages generated by that
  view. (Since the app generates alot of console messages)
  ###
  name: ""