module.exports = (app) ->
  console.log "[directives] initializing"
  app.directive "compClassifiedlist", require "./components/classified-list"
  app.directive "ngImageLoader",      require "./ngImageLoader"
  app.directive "ngLikeViewport",     require "./ngLikeViewport"
  app.directive "ngMasonry",          require "./ngMasonry"
  app.directive "ngModelFile",        require "./ngModelFile"
  app.directive "ngRatio",            require "./ngRatio"
  app.directive "ngScroll",           require "./ngScroll"
  app.directive "ngScrollupClass",    require "./ngScrollupClass"