/* Categories */
db.categories.drop();
db.categories.insert([
	{ name:'For Sale', children: [
		{ _id: ObjectId(), name:'Art' },
		{ _id: ObjectId(), name:'Baby/Kids items' },
		{ _id: ObjectId(), name:'Bicycles' },
		{ _id: ObjectId(), name:'Books' },
		{ _id: ObjectId(), name:'Business/Industrial' },
		{ _id: ObjectId(), name:'CDs/DVDs/Records' },
		{ _id: ObjectId(), name:'Clothing/Accessories' },
		{ _id: ObjectId(), name:'Collectibles/Antiques' },
		{ _id: ObjectId(), name:'Computers/Software' },
		{ _id: ObjectId(), name:'Electronics' },
		{ _id: ObjectId(), name:'Furniture' },
		{ _id: ObjectId(), name:'Gaming' },
		{ _id: ObjectId(), name:'Health/Beauty Products' },
		{ _id: ObjectId(), name:'Hobbies/Crafts' },
		{ _id: ObjectId(), name:'Home Appliances' },
		{ _id: ObjectId(), name:'Home/Garden' },
		{ _id: ObjectId(), name:'Household Goods' },
		{ _id: ObjectId(), name:'Jewellery/Watches' },
		{ _id: ObjectId(), name:'Mobile Phones' },
		{ _id: ObjectId(), name:'Musical Instruments' },
		{ _id: ObjectId(), name:'Sporting/Exercise' },
		{ _id: ObjectId(), name:'Tickets' },
		{ _id: ObjectId(), name:'Toys/Games' },
		{ _id: ObjectId(), name:'Other' },
	]},
	{ name:'Vehicles', children: [
		{ _id: ObjectId(), name:'Cars' },
		{ _id: ObjectId(), name:'Family' },
		{ _id: ObjectId(), name:'Classics Cars' },
		{ _id: ObjectId(), name:'Exotics' },
		{ _id: ObjectId(), name:'Motorcycles/Motorbikes' },
		{ _id: ObjectId(), name:'Trucks/Lorries' },
		{ _id: ObjectId(), name:'Boats' },
		{ _id: ObjectId(), name:'Aircraft &amp; Aviation' },
		{ _id: ObjectId(), name:'Heavy Equipment' },
		{ _id: ObjectId(), name:'Construction Machinery' },
		{ _id: ObjectId(), name:'Caravans/Motorhomes' },
		{ _id: ObjectId(), name:'Parts/Accessories' },
		{ _id: ObjectId(), name:'Other' }
	]},
	{ name:'Community', children: [
		{ _id: ObjectId(), name:'Artists' },
		{ _id: ObjectId(), name:'Babysitter' },
		{ _id: ObjectId(), name:'Child Care' },
		{ _id: ObjectId(), name:'Elderly Home Assistance' },
		{ _id: ObjectId(), name:'Household Help' },
		{ _id: ObjectId(), name:'Lost/Found' },
		{ _id: ObjectId(), name:'Musicians/Bands' },
		{ _id: ObjectId(), name:'Pet Sitting' },
		{ _id: ObjectId(), name:'Rideshare/Carpool' },
		{ _id: ObjectId(), name:'Skills/Language Swap' },
		{ _id: ObjectId(), name:'Other' }
	]},
	{ name:'For Rent', children: [
		{ _id: ObjectId(), name:'Commercial Space' },
		{ _id: ObjectId(), name:'Flats' },
		{ _id: ObjectId(), name:'Flatshares/Rooms' },
		{ _id: ObjectId(), name:'Holiday Rentals' },
		{ _id: ObjectId(), name:'Houses' },
		{ _id: ObjectId(), name:'Offices' },
		{ _id: ObjectId(), name:'Parking' },
		{ _id: ObjectId(), name:'Short Term' },
		{ _id: ObjectId(), name:'Storage' },
		{ _id: ObjectId(), name:'Other' }
	]},
	{ name:'Real Estate', children: [
		{ _id: ObjectId(), name:'Commercial Space for Sale' },
		{ _id: ObjectId(), name:'Flats for Sale' },
		{ _id: ObjectId(), name:'Houses for Sale' },
		{ _id: ObjectId(), name:'Land for Sale' },
		{ _id: ObjectId(), name:'Vacation Property' },
		{ _id: ObjectId(), name:'Farm & Ranch' },
		{ _id: ObjectId(), name:'Other' }
	]},
	{ name:'Services', children: [
		{ _id: ObjectId(), name:'Automotive Services' },
		{ _id: ObjectId(), name:'Animal/Pet Services' },
		{ _id: ObjectId(), name:'Business Services' },
		{ _id: ObjectId(), name:'Career/HR Services' },
		{ _id: ObjectId(), name:'Child &amp; Elderly Care' },
		{ _id: ObjectId(), name:'Cleaning Services' },
		{ _id: ObjectId(), name:'Computer/Tech Help' },
		{ _id: ObjectId(), name:'Construction/Labour' },
		{ _id: ObjectId(), name:'Creative/Design Services' },
		{ _id: ObjectId(), name:'Esoteric' },
		{ _id: ObjectId(), name:'Event Services' },
		{ _id: ObjectId(), name:'Health/Beauty Services' },
		{ _id: ObjectId(), name:'Home Services' },
		{ _id: ObjectId(), name:'Insurance/Financial Services' },
		{ _id: ObjectId(), name:'Lawn/Garden Services' },
		{ _id: ObjectId(), name:'Legal Services' },
		{ _id: ObjectId(), name:'Moving/Storage Services' },
		{ _id: ObjectId(), name:'Office Services' },
		{ _id: ObjectId(), name:'Real Estate Services' },
		{ _id: ObjectId(), name:'Translation' },
		{ _id: ObjectId(), name:'Travel Services' },
		{ _id: ObjectId(), name:'Tuitions &amp; Lessons' },
		{ _id: ObjectId(), name:'Web Services' },
		{ _id: ObjectId(), name: 'Other' }
	]},
	{ name:'Pets', children: [
		{ _id: ObjectId(), name:'Cats, kittens' },
		{ _id: ObjectId(), name:'Dogs, puppies' },
		{ _id: ObjectId(), name:'Birds' },
		{ _id: ObjectId(), name:'Exotics' },
		{ _id: ObjectId(), name:'Fish' },
		{ _id: ObjectId(), name:'Accessories' },
		{ _id: ObjectId(), name:'Supplies' },
		{ _id: ObjectId(), name:'Lost Pets' },
		{ _id: ObjectId(), name:'Other' }
	]},
	{ name:'Classes', children: [
		{ _id: ObjectId(), name:'Art/Music/Dance Classes' },
		{ _id: ObjectId(), name:'Computer Classes' },
		{ _id: ObjectId(), name:'Continuing Education' },
		{ _id: ObjectId(), name:'Language Classes' },
		{ _id: ObjectId(), name:'Sports Wellness Classes' },
		{ _id: ObjectId(), name:'Tutors' },
		{ _id: ObjectId(), name:'Other' }
	]},
	{ name:'Jobs', children: [
		{ _id: ObjectId(), name:'Administrative/Support' },
		{ _id: ObjectId(), name:'Agents/Dealers' },
		{ _id: ObjectId(), name:'Arts/Culture' },
		{ _id: ObjectId(), name:'Bankers/Brokers' },
		{ _id: ObjectId(), name:'Construction/Labour' },
		{ _id: ObjectId(), name:'Customer Service/Call Centre' },
		{ _id: ObjectId(), name:'Design/Architecture' },
		{ _id: ObjectId(), name:'Education/Training' },
		{ _id: ObjectId(), name:'Engineering' },
		{ _id: ObjectId(), name:'Executive/Management' },
		{ _id: ObjectId(), name:'Government/Public Service' },
		{ _id: ObjectId(), name:'Health Care' },
		{ _id: ObjectId(), name:'Hospitality/Tourism/Travel' },
		{ _id: ObjectId(), name:'Information Technology' },
		{ _id: ObjectId(), name:'Internships' },
		{ _id: ObjectId(), name:'Legal/Consulting/HR' },
		{ _id: ObjectId(), name:'Manufacturing' },
		{ _id: ObjectId(), name:'Marketing/Advertising/PR' },
		{ _id: ObjectId(), name:'Part Time Jobs/Side Jobs' },
		{ _id: ObjectId(), name:'Retail/Food/Wholesale' },
		{ _id: ObjectId(), name:'Sales/Distribution' },
		{ _id: ObjectId(), name:'Service' },
		{ _id: ObjectId(), name:'Social Work/Nonprofit' },
		{ _id: ObjectId(), name:'Traineeships' },
		{ _id: ObjectId(), name:'Transportation/Logistics' },
		{ _id: ObjectId(), name:'Other' }
	]},
	{ name:'Personal', children: [
		{ _id: ObjectId(), name:'Seeking Lifetime Partner' },
		{ _id: ObjectId(), name:'Casual Encounters/Friends' },
		{ _id: ObjectId(), name:'Missed Connections' },
		{ _id: ObjectId(), name:'Penpals' },
		{ _id: ObjectId(), name:'Seeking Activity Partners' },
		{ _id: ObjectId(), name:'Seeking Language Exchange' },
		{ _id: ObjectId(), name:'Other' }
	]}
]);


/* Locations */
db.locations.drop();
db.locations.insert([
	{ name: 'Abdullah Al-Salem' },
	{ name: 'Abraq Khaitan' },
	{ name: 'Abu Fteira' },
	{ name: 'Abu Halifa' },
	{ name: 'Adiliya' },
	{ name: 'Adān' },
	{ name: 'Ahmadi' },
	{ name: 'Al-Jabriya' },
	{ name: 'Al-Zour' },
	{ name: 'Andalus' },
	{ name: 'Ardiyah' },
	{ name: 'Bayan' },
	{ name: 'Bayān' },
	{ name: 'Bi-di' },
	{ name: 'Bnied Al-Gar' },
	{ name: 'Daiya' },
	{ name: 'Dasman' },
	{ name: 'Doha' },
	{ name: 'Fahaheel' },
	{ name: 'Faiha' },
	{ name: 'Fardaws' },
	{ name: 'Farwaniyah' },
	{ name: 'Fintās' },
	{ name: 'Funaitīs' },
	{ name: 'Ghirnata' },
	{ name: 'Hadiya' },
	{ name: 'Hawally' },
	{ name: 'Hittin' },
	{ name: 'Jabir al-Ahmad City' },
	{ name: 'Jabriya' },
	{ name: 'Jahra' },
	{ name: 'Jibla' },
	{ name: 'Jleeb Al-Shuyoukh' },
	{ name: 'Keifan' },
	{ name: 'Khaitan' },
	{ name: 'Khaldiya' },
	{ name: 'Kuwait City' },
	{ name: 'Mahboula' },
	{ name: 'Maidan Hawalli' },
	{ name: 'Mangaf' },
	{ name: 'Mansouriya' },
	{ name: 'Mirgāb' },
	{ name: 'Mishref' },
	{ name: 'Misīla' },
	{ name: 'Mubarak aj-Jabir suburb' },
	{ name: 'Mubarak al-Kabeer' },
	{ name: 'Nahdha' },
	{ name: 'Nigra' },
	{ name: 'Nuzha' },
	{ name: 'Omariya' },
	{ name: 'Qadsiya' },
	{ name: 'Qurain' },
	{ name: 'Qurtuba' },
	{ name: 'Qusūr' },
	{ name: 'Rabiya' },
	{ name: 'Rai' },
	{ name: 'Rawdah' },
	{ name: 'Riqqah' },
	{ name: 'Rumaithiya' },
	{ name: 'Sabah Al-Nasser' },
	{ name: 'Sabah Al-Salem' },
	{ name: 'Sabahiyah' },
	{ name: 'Sabhān' },
	{ name: 'Salhiya' },
	{ name: 'Salmiya' },
	{ name: 'Salwa' },
	{ name: 'Sawābir' },
	{ name: 'Sha-ab' },
	{ name: 'Shammiya' },
	{ name: 'Sharq' },
	{ name: 'Shuwaikh' },
	{ name: 'Sulaibikhat' },
	{ name: 'Surra' },
	{ name: 'Udailiya' },
	{ name: 'Wafra' },
	{ name: 'Yarmūk' },
	{ name: 'None' }
]);