/* Categories */
db.categories.drop();
db.categories.insert([
	{ name:'Classes' },
	{ name:'Community' },
	{ name:'For Rent' },
	{ name:'For Sale' },
	{ name:'Jobs' },
	{ name:'Matrimonial' },
	{ name:'Personal' },
	{ name:'Pets' },
	{ name:'Services' },
	{ name:'Vehicles' },
	{ name:'Others' }
]);


/* Locations */
db.locations.drop();
db.locations.insert([
	{ name: 'Abdullah Al-Salem' },
	{ name: 'Abraq Khaitan' },
	{ name: 'Abu Fteira' },
	{ name: 'Abu Halifa' },
	{ name: 'Adiliya' },
	{ name: 'Adān' },
	{ name: 'Ahmadi' },
	{ name: 'Al-Jabriya' },
	{ name: 'Al-Zour' },
	{ name: 'Andalus' },
	{ name: 'Ardiyah' },
	{ name: 'Bayan' },
	{ name: 'Bayān' },
	{ name: 'Bi-di' },
	{ name: 'Bnied Al-Gar' },
	{ name: 'Daiya' },
	{ name: 'Dasman' },
	{ name: 'Doha' },
	{ name: 'Fahaheel' },
	{ name: 'Faiha' },
	{ name: 'Fardaws' },
	{ name: 'Farwaniyah' },
	{ name: 'Fintās' },
	{ name: 'Funaitīs' },
	{ name: 'Ghirnata' },
	{ name: 'Hadiya' },
	{ name: 'Hawally' },
	{ name: 'Hittin' },
	{ name: 'Jabir al-Ahmad City' },
	{ name: 'Jabriya' },
	{ name: 'Jahra' },
	{ name: 'Jibla' },
	{ name: 'Jleeb Al-Shuyoukh' },
	{ name: 'Keifan' },
	{ name: 'Khaitan' },
	{ name: 'Khaldiya' },
	{ name: 'Kuwait City' },
	{ name: 'Mahboula' },
	{ name: 'Maidan Hawalli' },
	{ name: 'Mangaf' },
	{ name: 'Mansouriya' },
	{ name: 'Mirgāb' },
	{ name: 'Mishref' },
	{ name: 'Misīla' },
	{ name: 'Mubarak aj-Jabir suburb' },
	{ name: 'Mubarak al-Kabeer' },
	{ name: 'Nahdha' },
	{ name: 'Nigra' },
	{ name: 'Nuzha' },
	{ name: 'Omariya' },
	{ name: 'Qadsiya' },
	{ name: 'Qurain' },
	{ name: 'Qurtuba' },
	{ name: 'Qusūr' },
	{ name: 'Rabiya' },
	{ name: 'Rai' },
	{ name: 'Rawdah' },
	{ name: 'Riqqah' },
	{ name: 'Rumaithiya' },
	{ name: 'Sabah Al-Nasser' },
	{ name: 'Sabah Al-Salem' },
	{ name: 'Sabahiyah' },
	{ name: 'Sabhān' },
	{ name: 'Salhiya' },
	{ name: 'Salmiya' },
	{ name: 'Salwa' },
	{ name: 'Sawābir' },
	{ name: 'Sha-ab' },
	{ name: 'Shammiya' },
	{ name: 'Sharq' },
	{ name: 'Shuwaikh' },
	{ name: 'Sulaibikhat' },
	{ name: 'Surra' },
	{ name: 'Udailiya' },
	{ name: 'Wafra' },
	{ name: 'Yarmūk' },
	{ name: 'None' }
]);