TRUNCATE `category`;
INSERT INTO  `category` (`id`, `parent`, `name`) VALUES
	(1, NULL, 'For Sale'),
	(2, NULL, 'Vehicles'),
	(3, NULL, 'Community'),
	(4, NULL, 'For Rent'),
	(5, NULL, 'Real Estate'),
	(6, NULL, 'Services'),
	(7, NULL, 'Pets'),
	(8, NULL, 'Classes'),
	(9, NULL, 'Jobs'),
	(10, NULL, 'Personal'),
	-- Sale
	(NULL, 1, 'Art'),
	(NULL, 1, 'Baby/Kids items'),
	(NULL, 1, 'Bicycles'),
	(NULL, 1, 'Books'),
	(NULL, 1, 'Business/Industrial'),
	(NULL, 1, 'CDs/DVDs/Records'),
	(NULL, 1, 'Clothing/Accessories'),
	(NULL, 1, 'Collectibles/Antiques'),
	(NULL, 1, 'Computers/Software'),
	(NULL, 1, 'Electronics'),
	(NULL, 1, 'Furniture'),
	(NULL, 1, 'Gaming'),
	(NULL, 1, 'Health/Beauty Products'),
	(NULL, 1, 'Hobbies/Crafts'),
	(NULL, 1, 'Home Appliances'),
	(NULL, 1, 'Home/Garden'),
	(NULL, 1, 'Household Goods'),
	(NULL, 1, 'Jewellery/Watches'),
	(NULL, 1, 'Mobile Phones'),
	(NULL, 1, 'Musical Instruments'),
	(NULL, 1, 'Sporting/Exercise'),
	(NULL, 1, 'Tickets'),
	(NULL, 1, 'Toys/Games'),
	(NULL, 1, 'Other'),
	-- Vehicles
	(NULL, 2, 'Cars'),
	(NULL, 2, 'Family'),
	(NULL, 2, 'Classics Cars'),
	(NULL, 2, 'Exotics'),
	(NULL, 2, 'Motorcycles/Motorbikes'),
	(NULL, 2, 'Trucks/Lorries'),
	(NULL, 2, 'Boats'),
	(NULL, 2, 'Aircraft &amp; Aviation'),
	(NULL, 2, 'Heavy Equipment'),
	(NULL, 2, 'Construction Machinery'),
	(NULL, 2, 'Caravans/Motorhomes'),
	(NULL, 2, 'Parts/Accessories'),
	(NULL, 2, 'Other'),
	-- Community
	(NULL, 3, 'Artists'),
	(NULL, 3, 'Babysitter'),
	(NULL, 3, 'Child Care'),
	(NULL, 3, 'Elderly Home Assistance'),
	(NULL, 3, 'Household Help'),
	(NULL, 3, 'Lost/Found'),
	(NULL, 3, 'Musicians/Bands'),
	(NULL, 3, 'Pet Sitting'),
	(NULL, 3, 'Rideshare/Carpool'),
	(NULL, 3, 'Skills/Language Swap'),
	(NULL, 3, 'Other'),
	-- Rent
	(NULL, 4, 'Commercial Space'),
	(NULL, 4, 'Flats'),
	(NULL, 4, 'Flatshares/Rooms'),
	(NULL, 4, 'Holiday Rentals'),
	(NULL, 4, 'Houses'),
	(NULL, 4, 'Offices'),
	(NULL, 4, 'Parking'),
	(NULL, 4, 'Short Term'),
	(NULL, 4, 'Storage'),
	(NULL, 4, 'Other'),
	-- Real-estate
	(NULL, 5, 'Commercial Space for Sale'),
	(NULL, 5, 'Flats for Sale'),
	(NULL, 5, 'Houses for Sale'),
	(NULL, 5, 'Land for Sale'),
	(NULL, 5, 'Vacation Property'),
	(NULL, 5, 'Farm & Ranch'),
	(NULL, 5, 'Other'),
	-- Services
	(NULL, 6, 'Automotive Services'),
	(NULL, 7, 'Animal/Pet Services'),
	(NULL, 6, 'Business Services'),
	(NULL, 6, 'Career/HR Services'),
	(NULL, 6, 'Child &amp; Elderly Care'),
	(NULL, 6, 'Cleaning Services'),
	(NULL, 6, 'Computer/Tech Help'),
	(NULL, 6, 'Construction/Labour'),
	(NULL, 6, 'Creative/Design Services'),
	(NULL, 6, 'Esoteric'),
	(NULL, 6, 'Event Services'),
	(NULL, 6, 'Health/Beauty Services'),
	(NULL, 6, 'Home Services'),
	(NULL, 6, 'Insurance/Financial Services'),
	(NULL, 6, 'Lawn/Garden Services'),
	(NULL, 6, 'Legal Services'),
	(NULL, 6, 'Moving/Storage Services'),
	(NULL, 6, 'Office Services'),
	(NULL, 6, 'Real Estate Services'),
	(NULL, 6, 'Translation'),
	(NULL, 6, 'Travel Services'),
	(NULL, 6, 'Tuitions &amp; Lessons'),
	(NULL, 6, 'Web Services'),
	(NULL, 6,  'Other'),
	-- Pets
	(NULL, 7, 'Cats, kittens'),
	(NULL, 7, 'Dogs, puppies'),
	(NULL, 7, 'Birds'),
	(NULL, 7, 'Exotics'),
	(NULL, 7, 'Fish'),
	(NULL, 7, 'Accessories'),
	(NULL, 7, 'Supplies'),
	(NULL, 7, 'Lost Pets'),
	(NULL, 7, 'Other'),
	-- Classes
	(NULL, 8, 'Art/Music/Dance Classes'),
	(NULL, 8, 'Computer Classes'),
	(NULL, 8, 'Continuing Education'),
	(NULL, 8, 'Language Classes'),
	(NULL, 8, 'Sports Wellness Classes'),
	(NULL, 8, 'Tutors'),
	(NULL, 8, 'Other'),
	-- Jobs
	(NULL, 9, 'Administrative/Support'),
	(NULL, 9, 'Agents/Dealers'),
	(NULL, 9, 'Arts/Culture'),
	(NULL, 9, 'Bankers/Brokers'),
	(NULL, 9, 'Construction/Labour'),
	(NULL, 9, 'Customer Service/Call Centre'),
	(NULL, 9, 'Design/Architecture'),
	(NULL, 9, 'Education/Training'),
	(NULL, 9, 'Engineering'),
	(NULL, 9, 'Executive/Management'),
	(NULL, 9, 'Government/Public Service'),
	(NULL, 9, 'Health Care'),
	(NULL, 9, 'Hospitality/Tourism/Travel'),
	(NULL, 9, 'Information Technology'),
	(NULL, 9, 'Internships'),
	(NULL, 9, 'Legal/Consulting/HR'),
	(NULL, 9, 'Manufacturing'),
	(NULL, 9, 'Marketing/Advertising/PR'),
	(NULL, 9, 'Part Time Jobs/Side Jobs'),
	(NULL, 9, 'Retail/Food/Wholesale'),
	(NULL, 9, 'Sales/Distribution'),
	(NULL, 9, 'Service'),
	(NULL, 9, 'Social Work/Nonprofit'),
	(NULL, 9, 'Traineeships'),
	(NULL, 9, 'Transportation/Logistics'),
	(NULL, 9, 'Other'),
	-- Matrimonial
	(NULL, 10, 'Seeking Lifetime Partner'),
	-- (NULL, 10, 'Seeking Relationship'),
	(NULL, 10, 'Casual Encounters/Friends'),
	-- (NULL, 10, 'Couple Seeking Couple'),
	(NULL, 10, 'Missed Connections'),
	(NULL, 10, 'Penpals'),
	(NULL, 10, 'Seeking Activity Partners'),
	(NULL, 10, 'Seeking Language Exchange'),
	(NULL, 10, 'Other');

-- Languages
TRUNCATE `language`;
INSERT INTO  `language` (`name`) VALUES
	('English'),
	('Arabic');

-- Locations
TRUNCATE `location`;
INSERT INTO  `location` (`name`) VALUES
	('Abdullah Al-Salem'),
	('Abraq Khaitan'),
	('Abu Fteira'),
	('Abu Halifa'),
	('Adiliya'),
	('Adān'),
	('Ahmadi'),
	('Al-Jabriya'),
	('Al-Zour'),
	('Andalus'),
	('Ardiyah'),
	('Bayan'),
	('Bayān'),
	('Bi-di'),
	('Bnied Al-Gar'),
	('Daiya'),
	('Dasman'),
	('Doha'),
	('Fahaheel'),
	('Faiha'),
	('Fardaws'),
	('Farwaniyah'),
	('Fintās'),
	('Funaitīs'),
	('Ghirnata'),
	('Hadiya'),
	('Hawally'),
	('Hittin'),
	('Jabir al-Ahmad City'),
	('Jabriya'),
	('Jahra'),
	('Jibla'),
	('Jleeb Al-Shuyoukh'),
	('Keifan'),
	('Khaitan'),
	('Khaldiya'),
	('Kuwait City'),
	('Mahboula'),
	('Maidan Hawalli'),
	('Mangaf'),
	('Mansouriya'),
	('Mirgāb'),
	('Mishref'),
	('Misīla'),
	('Mubarak aj-Jabir suburb'),
	('Mubarak al-Kabeer'),
	('Nahdha'),
	('Nigra'),
	('Nuzha'),
	('Omariya'),
	('Qadsiya'),
	('Qurain'),
	('Qurtuba'),
	('Qusūr'),
	('Rabiya'),
	('Rai'),
	('Rawdah'),
	('Riqqah'),
	('Rumaithiya'),
	('Sabah Al-Nasser'),
	('Sabah Al-Salem'),
	('Sabahiyah'),
	('Sabhān'),
	('Salhiya'),
	('Salmiya'),
	('Salwa'),
	('Sawābir'),
	('Sha-ab'),
	('Shammiya'),
	('Sharq'),
	('Shuwaikh'),
	('Sulaibikhat'),
	('Surra'),
	('Udailiya'),
	('Wafra'),
	('Yarmūk');

-- Default root user
INSERT INTO `users`  VALUES
	(1, 'jon', '$2a$08$Lqahu8Yz/UWc3ZKeT9r0NuwiF/A0m2uvM5nnQRjg7NhrSNQzF1ALS',
		'jon@mail.com', 1, 0, NULL, NULL, NULL, NULL, NULL, '127.0.0.1',
		'2015-02-04 10:47:55', '2014-12-28 09:39:45', '2015-02-04 07:47:55');